/**
 * BRIAPI_collection copyLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, object, Schema, string } from '../schema';

export interface Success {
  refreshTokenExpiresIn: string;
  apiProductList: string;
  apiProductListJson: string[];
  organizationName: string;
  developerEmail: string;
  tokenType: string;
  issuedAt: string;
  clientId: string;
  accessToken: string;
  applicationName: string;
  scope: string;
  expiresIn: string;
  refreshCount: string;
  status: string;
}

export const successSchema: Schema<Success> = object({
  refreshTokenExpiresIn: ['refresh_token_expires_in', string()],
  apiProductList: ['api_product_list', string()],
  apiProductListJson: ['api_product_list_json', array(string())],
  organizationName: ['organization_name', string()],
  developerEmail: ['developer.email', string()],
  tokenType: ['token_type', string()],
  issuedAt: ['issued_at', string()],
  clientId: ['client_id', string()],
  accessToken: ['access_token', string()],
  applicationName: ['application_name', string()],
  scope: ['scope', string()],
  expiresIn: ['expires_in', string()],
  refreshCount: ['refresh_count', string()],
  status: ['status', string()],
});
